#
# BUILD FOR LOCAL DEVELOPMENT
#

FROM node:latest As development

WORKDIR /app

# this is jst the development part, for production implement other stages
## EXAMPLE

# Stage 2 - the production environment
# FROM nginx:1.17.9-alpine
# COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
